# As this is a forked repo, not upstream, workflows don't run by default, it'll need to be enabled:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories
name: Docs (Github Pages)

# As this workflow lives on non-default/master/main branch, it only runs when receiving a commit on this branch? (then checks the default branch workflows?)
# You can restrict to `push` and `pull_request` event triggers, with further restrictions to those commits being on a specific branch and/or matching a file path pattern:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#configuring-workflow-events
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
on:
  push:
    branches:
      - 'docs/docusaurus-demo'
    paths:
      - '.github/workflows/documentation-site.yml'
      - 'website/**'
  pull_request:
    branches:
      - 'docs/docusaurus-demo'
    paths:
      - '.github/workflows/documentation-site.yml'
      - 'website/**'

# Jobs will run shell commands from this subdirectory:
defaults:
  run:
    working-directory: website

jobs:
  test-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # First step for most actions, checkout the git repo/branch.
      - uses: actions/checkout@v2

      # Installs v14 LTS of Node. Uses cached version that Github replaces bi-weekly with latest updates for that version of Node.
      # https://github.com/actions/setup-node
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # Cache the yarn cache dir to speed up builds if dependencies haven't changed:
      # Caches are deleted if they've not been used in the past 7 days, or the total cache limit of 5GB is exceeded (oldest cache data is evicted first).
      # https://github.com/actions/cache
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          # If cache key does not have a match, `restore-keys` will check for previous cache keys with the given prefix and choose the most recent cache:
          # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
          restore-keys: ${{ runner.os }}-website-

      # Install project dependencies, then run the build script from `package.json`.
      # Outputs static docs for hosting to `website/build/`
      - run: yarn install --frozen-lockfile
      - run: yarn build
  deploy-docs:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-website-

      - run: yarn install --frozen-lockfile
      - run: yarn build

      # Popular action to deploy to gh-pages:
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy docs to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          # Assign the gh-pages branch commits to the official github-actions bot:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # https://api.github.com/users/github-actions%5Bbot%5D
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
