# As this is a forked repo, not upstream, workflows don't run by default, it'll need to be enabled:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories
name: MkDocs (Github Pages)

# As this workflow lives on non-default/master/main branch, it only runs when receiving a commit on this branch? (then checks the default branch workflows?)
# You can restrict to `push` and `pull_request` event triggers, with further restrictions to those commits being on a specific branch and/or matching a file path pattern:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#configuring-workflow-events
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
on:
  push:
    branches:
      - 'docs/demo-mkdocs'
    paths:
      - '.github/workflows/generate-docs.yml'
      - 'docs/**'
  pull_request:
    branches:
      - 'docs/demo-mkdocs'
    paths:
      - '.github/workflows/generate-docs.yml'
      - 'docs/**'

# Jobs will run shell commands from this subdirectory:
defaults:
  run:
    working-directory: docs

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build with mkdocs-material via Docker
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build with mkdocs-material via Docker
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
